### ISSUE TITLE
[pt-BR] Dúvida de chaves estrangeiras

### ISSUE THREAD

**Issue by diegolourenco** [YourAppRocks/eloquent-uuid#2]
Boa tarde, gostaria de saber como faço para adicionar uma chave estrangeira, por exemplo:
`
Schema::create('users', function (Blueprint $table) {
            $table->uuid('uuid');
           .
           .
});

Schema::create('contato', function (Blueprint $table) {
            $table->uuid('uuid');
            $table->unsignedInteger('uuid'); // Aqui como seria?
            $table->foreign('uuid')->references('uuid')->on('users');
});
`

**Comment by joaorobertopb** [comment]
Hey @DiegoLourenco ,

Você não pode user `unsignedInteger()` porque `uuid` é um campo `String`. Ok?
