### ISSUE TITLE
[pt-BR] Problemas ao obter uuid

### ISSUE THREAD

**Issue by joaoroyosilva** [YourAppRocks/eloquent-uuid#4]
Boa tarde pessoal, estou com problemas ao obter o uuid. Estou tendo um retorno de um número aleatório e não o uuid correto. O método findByUuid está funcionando. Alguém sabe o que pode ser? Abaixo segue um exemplo no tinker.
![Screenshot from 2020-01-21 16-12-21](https://user-images.githubusercontent.com/6354258/72839681-19c82080-3c69-11ea-8cf8-192b39a9ff2d.png)

**Comment by joaoroyosilva** [comment]
pelo que eu vi, está sendo retornado os inteiros até o primeiro caractere que é letra.

**Comment by joaoroyosilva** [comment]
Resolvi adicionando o código abaixo ao model

 protected $casts = [
        'id' => 'string'
    ];

**Comment by joaorobertopb** [comment]
Exato @joaoroyosilva é necessário fazer esse **casts**, quando o UUID é a chave primária da tabela.

Você pode fazer isso:

```php
protected $keyType = 'string';
```

Dessa maneira você informa para o **Eloquent** que o **Type** da chave é de fato **string**. 

Depois vou melhorar a documentação e alertar os usuários sobre isso.

**Comment by joaoroyosilva** [comment]
Entendi. Eu ainda estou tendo problemas ao salvar. Quando salvo, o objeto criado volta com "0" no id. Você tem alguma ideia do que pode ser?
